name: Generate Documentation

on:
  push:
    branches:
      - scientist
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm i
      - name: Generate Documentation
        run: npm run generate:doc

      - name: Commit changes
        run: |
          git config --global user.email "fantomitechno@gmail.com"
          git config --global user.name "fantomitechno"
          git add docs -f
          git commit -m "docs: Generate documentation."
          git push origin master
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: fantomitechno@gmail.com
          build_dir: docs
